### ISSUE TITLE
Problem with `tif_is_tokens_df()` function

### ISSUE THREAD

**Issue by lmullen** [ropensci/tif#6] opened 2018-03-13 01:11 UTC
```
library(tif)
library(magrittr)

tokens <- list(doc1 = c("aujourd'hui", "maman", "est", "morte"), doc2 = c("it", 
  "was", "a", "pleasure", "to", "burn"), doc3 = c("all", "this", "happened", 
  "more", "or", "less"))

tokens %>% tif_as_tokens_df() %>% tif_is_tokens_df()
#> [1] FALSE
```

I'd expect the output in the last line to be `TRUE`.

**Comment by taylor-arnold** [comment] 2018-03-13 03:19
Good point. Was being caused by the name of the second column in `tif_as_tokens_df`, which we had gone back and forth on what it should be called. Fixed with 90fba02

**Closed as completed** 2018-03-14 01:51 UTC
